version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.11"
  apt_packages:
    - graphviz
  jobs:
    post_build:
      - python -m sphinx.ext.intersphinx docs/_build/html/objects.inv
      - python -m sphinx.ext.doctest docs/
      - python -m sphinx.ext.coverage docs/
      - python -m sphinx.ext.linkcheck docs/

sphinx:
  configuration: docs/conf.py
  fail_on_warning: false
  builder: dirhtml

formats:
  - pdf
  - epub

python:
  install:
    - requirements: docs/requirements.txt
    - method: pip
      path: .
      extra_requirements:
        - docs

# Submodules configuration
submodules:
  include: all
  recursive: true