version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.11"
  jobs:
    post_checkout:
      - git fetch --unshallow || true
      - git fetch origin dev:dev
      - git checkout dev

sphinx:
  configuration: docs/conf.py
  fail_on_warning: false
  builder: html

formats:
  - pdf
  - epub

python:
  install:
    - method: pip
      path: .
      extra_requirements:
        - docs

# Submodules configuration
submodules:
  include: all
  recursive: true

# Translations configuration
translations:
  en: English
  ru: Russian