version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.11"
  jobs:
    pre_create_environment:
      - pip install sphinx-intl
    pre_build:
      - sphinx-build -b gettext docs/ docs/_build/gettext
      - sphinx-intl update -p docs/_build/gettext -l ru
  apt_packages:
    - gettext

sphinx:
  configuration: docs/conf.py
  fail_on_warning: false
  builder: html

formats:
  - pdf
  - epub

python:
  install:
    - requirements: docs/requirements.txt
    - method: pip
      path: .
      extra_requirements:
        - docs

# Submodules configuration
submodules:
  include: all
  recursive: true

# RTD Configuration
build:
  os: ubuntu-22.04
  tools:
    python: "3.11"

# Languages configuration
languages:
   en: docs/
   ru: docs/locale/ru/LC_MESSAGES/