version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.11"
  apt_packages:
    - graphviz

sphinx:
  configuration: docs/conf.py
  fail_on_warning: false
  builder: dirhtml

formats:
  - pdf
  - epub

python:
  install:
    - requirements: docs/requirements.txt
    - method: pip
      path: .
      extra_requirements:
        - docs

# Submodules configuration
submodules:
  include: all
  recursive: true

# Search configuration
search:
  ranking:
    api/*: -1
    examples/*: 2
    quickstart/*: 3
  ignore:
    - search.html
    - genindex.html
    - py-modindex.html
    - _static/*
    - _templates/*

# Analytics configuration
analytics:
  enabled: true
  anonymize_ip: true

# Build configuration
build:
  os: ubuntu-22.04
  tools:
    python: "3.11"
  apt_packages:
    - graphviz
  jobs:
    post_build:
      - python -m sphinx.ext.intersphinx docs/_build/html/objects.inv
      - python -m sphinx.ext.doctest docs/
      - python -m sphinx.ext.coverage docs/
      - python -m sphinx.ext.linkcheck docs/