version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.11"
  jobs:
    pre_build:
      - python -m sphinx.cmd.build -b gettext docs/ docs/_build/gettext
      - sphinx-intl update -p docs/_build/gettext -l ru

sphinx:
  configuration: docs/conf.py
  fail_on_warning: false
  builder: dirhtml

formats:
  - pdf
  - epub

python:
  install:
    - method: pip
      path: .
      extra_requirements:
        - docs

# Submodules configuration
submodules:
  include: all
  recursive: true