version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.11"

sphinx:
  configuration: docs/conf.py
  fail_on_warning: false
  builder: dirhtml

formats:
  - pdf
  - epub

python:
  install:
    - requirements: docs/requirements.txt
    - method: pip
      path: .
      extra_requirements:
        - docs

# Submodules configuration
submodules:
  include: all
  recursive: true

# Language configuration
sphinx:
  builder: dirhtml
  configuration: docs/conf.py
  fail_on_warning: false

# Language configuration
build:
  os: ubuntu-22.04
  tools:
    python: "3.11"
  jobs:
    post_checkout:
      - mkdir -p docs/_build/gettext
      - sphinx-build -b gettext docs/ docs/_build/gettext
      - sphinx-intl update -p docs/_build/gettext -l ru

# Domain configuration
domains:
  - name: docs.bykovk.pro
    https: true
    enforce_https: true
    canonical: true