version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.11"

sphinx:
  configuration: docs/conf.py
  fail_on_warning: false
  builder: html
  i18n:
    language:
      - en
      - ru
    build:
      - en
      - ru

python:
  install:
    - method: pip
      path: .
      extra_requirements:
        - docs